# SwiftLint Configuration

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Included paths
included:
  - bidding-mobile-ios-sdk
  - bidding-mobile-ios-sdkTests

# Excluded paths
excluded:
  - Pods
  - .build
  - DerivedData
  - build
  - bidding_mobile_ios_sdk.docc

# Reporter
reporter: "xcode"

# Line length (overridden)
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Function body length
function_body_length:
  warning: 100
  error: 200

# File length
file_length:
  warning: 500
  error: 1000

# Type body length
type_body_length:
  warning: 300
  error: 500

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Force casting
force_cast: warning
force_try: warning

# Identifier names
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok
    - no
    - x
    - y
    - z

# Type name
type_name:
  min_length: 3
  max_length: 50

# Variable name
variable_name:
  min_length: 2
  max_length: 50

